server:
    port: 18080

# 数据库配置
spring:
    datasource:
        url: jdbc:mysql://172.26.108.190:3306/njuTeacher?characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
