package com.nju171250.njuTeacher.mapper;

import com.nju171250.njuTeacher.model.RecordDoFavourite;
import com.nju171250.njuTeacher.model.RecordDoFavouriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordDoFavouriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    int countByExample(RecordDoFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    int deleteByExample(RecordDoFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    int insert(RecordDoFavourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    int insertSelective(RecordDoFavourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    List<RecordDoFavourite> selectByExample(RecordDoFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") RecordDoFavourite record, @Param("example") RecordDoFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    int updateByExample(@Param("record") RecordDoFavourite record, @Param("example") RecordDoFavouriteExample example);

    // TODO 查看用户是否已对某个评价进行点赞
    int countByUserIdAndCommentId(String userId, String commentId);

    // 查看用户已点过赞后的点赞情况
    boolean selectFavouriteSituationByUserIdAndCommentId(String userId, String commentId);
}