package com.nju171250.njuTeacher.model;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id_school
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String courseIdSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_id
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_type
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_academy
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String courseAcademy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_credit
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private Float courseCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_area
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String courseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_teacher
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    private String courseTeacher;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public Course(String courseId, String courseIdSchool, String teacherId, String courseName, String courseType, String courseAcademy, Float courseCredit, String courseArea, String courseTeacher) {
        this.courseId = courseId;
        this.courseIdSchool = courseIdSchool;
        this.teacherId = teacherId;
        this.courseName = courseName;
        this.courseType = courseType;
        this.courseAcademy = courseAcademy;
        this.courseCredit = courseCredit;
        this.courseArea = courseArea;
        this.courseTeacher = courseTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public Course() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id_school
     *
     * @return the value of course.course_id_school
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getCourseIdSchool() {
        return courseIdSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id_school
     *
     * @param courseIdSchool the value for course.course_id_school
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseIdSchool(String courseIdSchool) {
        this.courseIdSchool = courseIdSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_id
     *
     * @return the value of course.teacher_id
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_id
     *
     * @param teacherId the value for course.teacher_id
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_type
     *
     * @return the value of course.course_type
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getCourseType() {
        return courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_type
     *
     * @param courseType the value for course.course_type
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseType(String courseType) {
        this.courseType = courseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_academy
     *
     * @return the value of course.course_academy
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getCourseAcademy() {
        return courseAcademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_academy
     *
     * @param courseAcademy the value for course.course_academy
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseAcademy(String courseAcademy) {
        this.courseAcademy = courseAcademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_credit
     *
     * @return the value of course.course_credit
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public Float getCourseCredit() {
        return courseCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_credit
     *
     * @param courseCredit the value for course.course_credit
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseCredit(Float courseCredit) {
        this.courseCredit = courseCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_area
     *
     * @return the value of course.course_area
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getCourseArea() {
        return courseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_area
     *
     * @param courseArea the value for course.course_area
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseArea(String courseArea) {
        this.courseArea = courseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_teacher
     *
     * @return the value of course.course_teacher
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public String getCourseTeacher() {
        return courseTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_teacher
     *
     * @param courseTeacher the value for course.course_teacher
     *
     * @mbggenerated Sat Mar 16 09:08:39 CST 2019
     */
    public void setCourseTeacher(String courseTeacher) {
        this.courseTeacher = courseTeacher;
    }
}