package com.nju171250.njuTeacher.model;

public class RecordDoFavourite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_do_favourite.user_id
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_do_favourite.comment_id
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_do_favourite.isFavourited
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    private Boolean isfavourited;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public RecordDoFavourite(String userId, String commentId, Boolean isfavourited) {
        this.userId = userId;
        this.commentId = commentId;
        this.isfavourited = isfavourited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_do_favourite
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public RecordDoFavourite() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_do_favourite.user_id
     *
     * @return the value of record_do_favourite.user_id
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_do_favourite.user_id
     *
     * @param userId the value for record_do_favourite.user_id
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_do_favourite.comment_id
     *
     * @return the value of record_do_favourite.comment_id
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_do_favourite.comment_id
     *
     * @param commentId the value for record_do_favourite.comment_id
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_do_favourite.isFavourited
     *
     * @return the value of record_do_favourite.isFavourited
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public Boolean getIsfavourited() {
        return isfavourited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_do_favourite.isFavourited
     *
     * @param isfavourited the value for record_do_favourite.isFavourited
     *
     * @mbggenerated Fri Mar 15 22:57:40 CST 2019
     */
    public void setIsfavourited(Boolean isfavourited) {
        this.isfavourited = isfavourited;
    }
}