package com.nju171250.njuTeacher.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_state
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    private Boolean loginState;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    public User(String userId, Boolean loginState) {
        this.userId = userId;
        this.loginState = loginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_state
     *
     * @return the value of user.login_state
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    public Boolean getLoginState() {
        return loginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_state
     *
     * @param loginState the value for user.login_state
     *
     * @mbggenerated Mon Mar 11 20:03:45 CST 2019
     */
    public void setLoginState(Boolean loginState) {
        this.loginState = loginState;
    }
}